= Overview

== About Spring-Data-Eclipse-Store

A library to simplify using https://eclipsestore.io/[EclipseStore] in the https://spring.io/projects/spring-data/[Spring environment].

What makes this library special is, that it creates a xref:working-copies.adoc[working copy] of the data.
This way EclipseStore behaves almost exactly like relational database from a coding perspective.

== Features

The library provides following features:

* Enforces the
https://docs.spring.io/spring-data/jpa/reference/repositories/core-concepts.html[Spring data repository concept]
for EclipseStore by using xref:working-copies.adoc[working copies].
* xref:installation.adoc#drop-in-compatible[Drop in compatible] for your existing Spring application
* Utilizes *ultra-fast EclipseStore serializing and storing*
* Enables your application to select any https://docs.eclipsestore.io/manual/storage/storage-targets/index.html[EclipseStore target] (e.g.
https://docs.eclipsestore.io/manual/storage/storage-targets/sql-databases/postgresql.html[PostgreSQL],
https://docs.eclipsestore.io/manual/storage/storage-targets/blob-stores/aws-s3.html[AWS S3] or
https://github.com/xdev-software/eclipse-store-afs-ibm-cos[IBM COS])
* Can save up to *99%footnote:[If the COS Connector is used in the IBM Cloud instead of a PostgreSQL and approx. 10,000 entries with a total size of 1 GB of data are stored. (https://cloud.ibm.com/estimator/estimates[IBM Cloud Pricing], as of 08.01.2024)] of monthly costs* in the IBM Cloud and up to 82%footnote:[If the S3 connector is used instead of DynamoDB under the same conditions at AWS.
(https://calculator.aws/#/estimate?id=ab85cddf77f0d1aa0457111ed82785dfb836b1d8[AWS Pricing Calculator], as of 08.01.2024)] in the AWS Cloud
